version: "3"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: postgres
        ports:
            - 5438:5432
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
