CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS RESTAURANTS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    AVERAGERATING REAL CHECK (AVERAGERATING >= 1 AND AVERAGERATING <= 5),
    ISKOSHER BOOLEAN NOT NULL,
    CUISINES VARCHAR(60)[] NOT NULL
);

CREATE TABLE IF NOT EXISTS RATINGS (
    RESTAURANT_ID SERIAL REFERENCES RESTAURANTS(ID) ON DELETE CASCADE,
    RATING REAL CHECK (RATING >= 1 AND RATING <= 5)
);

CREATE TABLE IF NOT EXISTS DISHES (
    RESTAURANT_ID SERIAL REFERENCES RESTAURANTS(ID) ON DELETE CASCADE,
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    DESCRIPTION VARCHAR(120) NOT NULL,
    PRICE REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    ORDER_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ORDERITEM (
    ORDER_ID UUID REFERENCES ORDERS(ID),
    DISH_ID SERIAL REFERENCES DISHES(ID) ON DELETE CASCADE,
    AMOUNT INTEGER NOT NULL
);

CREATE DATABASE test_database WITH TEMPLATE postgres OWNER postgres;